version: "3"
services:
  api:
    image: node:11.13.0-alpine
    container_name: api
    volumes:
      - .:/app
    environment:
      - NODE_ENV=dev
      - SECRET=Ks10daK3g
      - DB_URL=mongodb://mongo:27017/imagerepo
      - UPLOAD_DIR=/app/uploads
    working_dir: /app
    command: npm run start:local
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none